language: node_js
node_js:
  - "8.9.1"
env:
  global:
    - MONGO_HOST=mongodb://localhost
    - MONGO_PORT=27017
    - MONGO_DB=coin-trend-travis
services:
  - mongodb
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - yarn test
notifications:
  email: false
